### ISSUE TITLE
JSON-LD context order not deterministic

### ISSUE THREAD

**Issue by DieterDePaepe** [Informatievlaanderen/OSLO-SpecificationGenerator#11]
The order in which the JSON-LD context elements are listed does not seem deterministic. This causes updates of the vocabulary to have unnecessary differences, making it harder to audit the actual differences between versions.

**Comment by EmidioStani** [comment]
Can the classes and properties be ordered alphabetically ? At least as human to check if a class/property is in ?

**Comment by bertvannuffelen** [comment]
What ever is chosen, make it so that a git diff is meaningfull. Otherwise it is much harder to assess.  So a human friendly order is not the objective for me, but a machine friendly that leads to stable diffs.

**Comment by jensscheerlinck** [comment]
Updated script to sort terms alphabetically in commit, see [commit](https://github.com/Informatievlaanderen/OSLO-SpecificationGenerator/commit/bfbecb13aaa87a7e539199733d92e81a94b06c00#comments).
