### ISSUE TITLE
Error in JSON-LD Context

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-SpecificationGenerator#30]
De response van https://data.vlaanderen.be/context/organisatie-basis.jsonld bevat volgende lijnen. De komma na "@id":"http://schema.org/logo" is niet toegestaan in JSON. Bijgevolg worden json-ld documenten die afhangen van het applicatieprofiel niet correct verwerkt.

		"logo":{
			"@id":"http://schema.org/logo",

		},

**Comment by bertvannuffelen** [comment]
fixed in toolchain 2.0
